// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2qB5FHIw-4yKNHFaC4QjKe_A3Uh2UoRU',
    appId: '1:171565949600:web:a540deaee89f075aaadfc5',
    messagingSenderId: '171565949600',
    projectId: 'starlink-system',
    authDomain: 'starlink-system.firebaseapp.com',
    storageBucket: 'starlink-system.firebasestorage.app',
    measurementId: 'G-GZE0NBR5MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAreGkbDLT3AYif_-MTNLL9IwUsDb3_BVY',
    appId: '1:171565949600:android:b0fe7afb1fff3a3faadfc5',
    messagingSenderId: '171565949600',
    projectId: 'starlink-system',
    storageBucket: 'starlink-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxsFSENHq3BSyZp0EQSANyHzqQtL1Z8bo',
    appId: '1:171565949600:ios:5cdd6d0e8473d073aadfc5',
    messagingSenderId: '171565949600',
    projectId: 'starlink-system',
    storageBucket: 'starlink-system.firebasestorage.app',
    iosBundleId: 'com.example.starlinkSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxsFSENHq3BSyZp0EQSANyHzqQtL1Z8bo',
    appId: '1:171565949600:ios:5cdd6d0e8473d073aadfc5',
    messagingSenderId: '171565949600',
    projectId: 'starlink-system',
    storageBucket: 'starlink-system.firebasestorage.app',
    iosBundleId: 'com.example.starlinkSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2qB5FHIw-4yKNHFaC4QjKe_A3Uh2UoRU',
    appId: '1:171565949600:web:098d52e57c59faf5aadfc5',
    messagingSenderId: '171565949600',
    projectId: 'starlink-system',
    authDomain: 'starlink-system.firebaseapp.com',
    storageBucket: 'starlink-system.firebasestorage.app',
    measurementId: 'G-GBR19LRKG3',
  );
}
